
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Award2 : Luban.BeanBase
{
    public Award2(JSONNode _buf) 
    {
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["num"].IsNumber) { throw new SerializationException(); }  Num = _buf["num"]; }
    }

    public static Award2 DeserializeAward2(JSONNode _buf)
    {
        return new Award2(_buf);
    }

    /// <summary>
    /// 奖励ID2
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 奖励数量2
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = 1973796245;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "num:" + Num + ","
        + "}";
    }
}
}

