
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// KV
/// </summary>
public sealed partial class cKeyValue : Luban.BeanBase
{
    public cKeyValue(JSONNode _buf) 
    {
        { if(!_buf["cKey"].IsString) { throw new SerializationException(); }  CKey = _buf["cKey"]; }
        { if(!_buf["cValue"].IsString) { throw new SerializationException(); }  CValue = _buf["cValue"]; }
    }

    public static cKeyValue DeserializecKeyValue(JSONNode _buf)
    {
        return new cKeyValue(_buf);
    }

    /// <summary>
    /// key
    /// </summary>
    public readonly string CKey;
    /// <summary>
    /// value
    /// </summary>
    public readonly string CValue;
   
    public const int __ID__ = 2007529429;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cKey:" + CKey + ","
        + "cValue:" + CValue + ","
        + "}";
    }
}
}

