
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Fight.TbRank TbRank {get; }
    public Fight.TbTest1 TbTest1 {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbRank = new Fight.TbRank(loader("fight_tbrank"));
        TbTest1 = new Fight.TbTest1(loader("fight_tbtest1"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbRank.ResolveRef(this);
        TbTest1.ResolveRef(this);
    }
}

}
