
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Loading
{ 
    /// <summary>
    /// Loading类型
    /// </summary>
    public enum LoadingType
    {
        /// <summary>
        /// 默认
        /// </summary>
        Default = 0,
        /// <summary>
        /// 水族馆
        /// </summary>
        Aquarium = 1,
        /// <summary>
        /// 竞技
        /// </summary>
        Match = 2,
        /// <summary>
        /// 冰钓
        /// </summary>
        Ice = 3,
        /// <summary>
        /// 路亚钓
        /// </summary>
        Lure = 4,
        /// <summary>
        /// 巨物钓
        /// </summary>
        Giant = 5,
        /// <summary>
        /// 秘境
        /// </summary>
        Secret = 6,
        /// <summary>
        /// 切换账号
        /// </summary>
        SwitchAccount = 7,
        /// <summary>
        /// 从场景退出
        /// </summary>
        ExitScene = 8,
        /// <summary>
        /// 新手第1个loading图
        /// </summary>
        Guide1 = 50,
        /// <summary>
        /// 新手第2个loading图
        /// </summary>
        Guide2 = 51,
        /// <summary>
        /// 新手第3个loading图
        /// </summary>
        Guide3 = 52,
        /// <summary>
        /// 全局loading
        /// </summary>
        Global = 99,
    }

} 

