
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Loading
{
public sealed partial class NewLoadingRule : Luban.BeanBase
{
    public NewLoadingRule(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (Loading.LoadingType)_buf["Type"].AsInt; }
        { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["SubTitle"].IsString) { throw new SerializationException(); }  SubTitle = _buf["SubTitle"]; }
        { if(!_buf["TipDesc"].IsString) { throw new SerializationException(); }  TipDesc = _buf["TipDesc"]; }
        { if(!_buf["IsOpen"].IsNumber) { throw new SerializationException(); }  IsOpen = _buf["IsOpen"]; }
        { if(!_buf["OpenLevel"].IsNumber) { throw new SerializationException(); }  OpenLevel = _buf["OpenLevel"]; }
        { if(!_buf["WeightType"].IsNumber) { throw new SerializationException(); }  WeightType = (Loading.WeightType)_buf["WeightType"].AsInt; }
        { var __json0 = _buf["Weight"]; if(!__json0.IsArray) { throw new SerializationException(); } Weight = new System.Collections.Generic.List<Loading.WeightConfig>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Loading.WeightConfig __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Loading.WeightConfig.DeserializeWeightConfig(__e0);  }  Weight.Add(__v0); }   }
        { var __json0 = _buf["GlobalLoadingSwitch"]; if(!__json0.IsArray) { throw new SerializationException(); } GlobalLoadingSwitch = new System.Collections.Generic.List<Loading.LoadingType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Loading.LoadingType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (Loading.LoadingType)__e0.AsInt; }  GlobalLoadingSwitch.Add(__v0); }   }
        { var __json0 = _buf["ImagePaths"]; if(!__json0.IsArray) { throw new SerializationException(); } ImagePaths = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ImagePaths.Add(__v0); }   }
    }

    public static NewLoadingRule DeserializeNewLoadingRule(JSONNode _buf)
    {
        return new Loading.NewLoadingRule(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 加载类型
    /// </summary>
    public readonly Loading.LoadingType Type;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 副标题
    /// </summary>
    public readonly string SubTitle;
    /// <summary>
    /// 小贴士文案
    /// </summary>
    public readonly string TipDesc;
    /// <summary>
    /// 开关
    /// </summary>
    public readonly int IsOpen;
    /// <summary>
    /// 开启等级
    /// </summary>
    public readonly int OpenLevel;
    /// <summary>
    /// 权重类型
    /// </summary>
    public readonly Loading.WeightType WeightType;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly System.Collections.Generic.List<Loading.WeightConfig> Weight;
    /// <summary>
    /// 全局loading开关
    /// </summary>
    public readonly System.Collections.Generic.List<Loading.LoadingType> GlobalLoadingSwitch;
    /// <summary>
    /// 资源图
    /// </summary>
    public readonly System.Collections.Generic.List<string> ImagePaths;
   
    public const int __ID__ = -2058995766;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Weight) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Title:" + Title + ","
        + "SubTitle:" + SubTitle + ","
        + "TipDesc:" + TipDesc + ","
        + "IsOpen:" + IsOpen + ","
        + "OpenLevel:" + OpenLevel + ","
        + "WeightType:" + WeightType + ","
        + "Weight:" + Luban.StringUtil.CollectionToString(Weight) + ","
        + "GlobalLoadingSwitch:" + Luban.StringUtil.CollectionToString(GlobalLoadingSwitch) + ","
        + "ImagePaths:" + Luban.StringUtil.CollectionToString(ImagePaths) + ","
        + "}";
    }
}
}

