
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Loading
{
public partial class TbNewLoadingRule
{
    private readonly System.Collections.Generic.Dictionary<int, Loading.NewLoadingRule> _dataMap;
    private readonly System.Collections.Generic.List<Loading.NewLoadingRule> _dataList;
    
    public TbNewLoadingRule(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Loading.NewLoadingRule>();
        _dataList = new System.Collections.Generic.List<Loading.NewLoadingRule>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Loading.NewLoadingRule _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Loading.NewLoadingRule.DeserializeNewLoadingRule(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Loading.NewLoadingRule> DataMap => _dataMap;
    public System.Collections.Generic.List<Loading.NewLoadingRule> DataList => _dataList;

    public Loading.NewLoadingRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Loading.NewLoadingRule Get(int key) => _dataMap[key];
    public Loading.NewLoadingRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

