
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Loading
{ 
    /// <summary>
    /// 权重类型
    /// </summary>
    public enum WeightType
    {
        /// <summary>
        /// 按唯一权重
        /// </summary>
        None = 0,
        /// <summary>
        /// 根据活动进行的天数计算权重
        /// </summary>
        ActivityDays = 1,
        /// <summary>
        /// 根据玩家当前等级计算权重
        /// </summary>
        PlayerLevel = 2,
    }

} 

