
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Loading
{
/// <summary>
/// 权重配置项
/// </summary>
public sealed partial class WeightConfig : Luban.BeanBase
{
    public WeightConfig(JSONNode _buf) 
    {
        { if(!_buf["Condition"].IsNumber) { throw new SerializationException(); }  Condition = _buf["Condition"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
    }

    public static WeightConfig DeserializeWeightConfig(JSONNode _buf)
    {
        return new Loading.WeightConfig(_buf);
    }

    /// <summary>
    /// 条件值
    /// </summary>
    public readonly int Condition;
    /// <summary>
    /// 权重值
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -1524388980;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Condition:" + Condition + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}
}

