// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace HotUpdate {

  #region Messages
  /// <summary>
  ///测试
  /// </summary>
  public partial class Test : pb::IMessage {
    private static readonly pb::MessageParser<Test> _parser = new pb::MessageParser<Test>(() => (Test)MessagePool.Instance.Fetch(typeof(Test)));
    public static pb::MessageParser<Test> Parser { get { return _parser; } }

    public Test Clone(){
      Test newOne = new Test();
      newOne.test_ = test_;
      newOne.test2_ = test2_;
      return newOne;
    }

    public Test MergeFrom(Test other){
      test_ = other.test_;
      test2_ = other.test2_;
      return this;
    }

    private int test_;
    /// <summary>
    ///测试数字1
    /// </summary>
    public int Test_ {
      get { return test_; }
      set {
        test_ = value;
      }
    }

    private long test2_;
    /// <summary>
    ///测试数字2
    /// </summary>
    public long Test2 {
      get { return test2_; }
      set {
        test2_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Test_ != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(Test_);
      }
      if (Test2 != 0L) {
        output.WriteRawTag(16);
        output.WriteSInt64(Test2);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Test_ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Test_);
      }
      if (Test2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Test2);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Test_ = input.ReadSInt32();
            break;
          }
          case 16: {
            Test2 = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
