//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由UI绑定工具自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using Core.Runtime;

namespace HotUpdate
{
    [SourceAttribute("Assets/GameRes/Prefabs/UI/Loading/CommonLoading")]
    public partial class CommonLoadingView
    {
        ComponentItemKey _componentItemKey;

        private UnityEngine.UI.Image _Image_bg;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_title;
        private UnityEngine.RectTransform _RectTransform_titleDescBg;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_titleDesc;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_content;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_process;
        private UnityEngine.UI.Slider _Slider_slider;
        private UnityEngine.RectTransform _RectTransform_loadingtitlebg;
        private UnityEngine.RectTransform _RectTransform_gameTips;

        protected ComponentItemKey componentItemKey
        {
            get
            {
                if(_componentItemKey == null)
                    _componentItemKey = transform.GetComponent<ComponentItemKey>();
                return _componentItemKey;
            }
        }

        public UnityEngine.UI.Image Image_bg
        {
            get
            {
                if(_Image_bg == null)
                    _Image_bg = componentItemKey.GetObject<UnityEngine.UI.Image>("Image_bg");
                return _Image_bg;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_title
        {
            get
            {
                if(_TextMeshProUGUI_title == null)
                    _TextMeshProUGUI_title = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_title");
                return _TextMeshProUGUI_title;
            }
        }

        public UnityEngine.RectTransform RectTransform_titleDescBg
        {
            get
            {
                if(_RectTransform_titleDescBg == null)
                    _RectTransform_titleDescBg = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_titleDescBg");
                return _RectTransform_titleDescBg;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_titleDesc
        {
            get
            {
                if(_TextMeshProUGUI_titleDesc == null)
                    _TextMeshProUGUI_titleDesc = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_titleDesc");
                return _TextMeshProUGUI_titleDesc;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_content
        {
            get
            {
                if(_TextMeshProUGUI_content == null)
                    _TextMeshProUGUI_content = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_content");
                return _TextMeshProUGUI_content;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_process
        {
            get
            {
                if(_TextMeshProUGUI_process == null)
                    _TextMeshProUGUI_process = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_process");
                return _TextMeshProUGUI_process;
            }
        }

        public UnityEngine.UI.Slider Slider_slider
        {
            get
            {
                if(_Slider_slider == null)
                    _Slider_slider = componentItemKey.GetObject<UnityEngine.UI.Slider>("Slider_slider");
                return _Slider_slider;
            }
        }

        public UnityEngine.RectTransform RectTransform_loadingtitlebg
        {
            get
            {
                if(_RectTransform_loadingtitlebg == null)
                    _RectTransform_loadingtitlebg = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_loadingtitlebg");
                return _RectTransform_loadingtitlebg;
            }
        }

        public UnityEngine.RectTransform RectTransform_gameTips
        {
            get
            {
                if(_RectTransform_gameTips == null)
                    _RectTransform_gameTips = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_gameTips");
                return _RectTransform_gameTips;
            }
        }

        /// <summary>
        /// 绑定按钮点击事件
        /// </summary>
        protected virtual void BindButtonEvents()
        {
        }

        /// <summary>
        /// 解绑按钮点击事件
        /// </summary>
        protected virtual void UnbindButtonEvents()
        {
        }

        protected virtual void ReleaseComponent()
        {
            UnbindButtonEvents();

            _Image_bg = null;
            _TextMeshProUGUI_title = null;
            _RectTransform_titleDescBg = null;
            _TextMeshProUGUI_titleDesc = null;
            _TextMeshProUGUI_content = null;
            _TextMeshProUGUI_process = null;
            _Slider_slider = null;
            _RectTransform_loadingtitlebg = null;
            _RectTransform_gameTips = null;
            _componentItemKey = null;
        }
    }
}
