//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由UI绑定工具自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using Core.Runtime;

namespace HotUpdate
{
    [SourceAttribute("Assets/GameRes/Prefabs/UI/Loading/CommonLoading")]
    public partial class CommonLoadingView
    {
        ComponentItemKey _componentItemKey;

        private UnityEngine.UI.Image _Image_Bg;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_Title;
        private UnityEngine.RectTransform _RectTransform_TitleDescBg;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_TitleDesc;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_Content;
        private TMPro.TextMeshProUGUI _TextMeshProUGUI_Process;
        private UnityEngine.RectTransform _RectTransform_LoadingTitlebg;
        private UnityEngine.RectTransform _RectTransform_GameTips;
        private UnityEngine.UI.Image _Image_Slider;

        protected ComponentItemKey componentItemKey
        {
            get
            {
                if(_componentItemKey == null)
                    _componentItemKey = transform.GetComponent<ComponentItemKey>();
                return _componentItemKey;
            }
        }

        public UnityEngine.UI.Image Image_Bg
        {
            get
            {
                if(_Image_Bg == null)
                    _Image_Bg = componentItemKey.GetObject<UnityEngine.UI.Image>("Image_Bg");
                return _Image_Bg;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_Title
        {
            get
            {
                if(_TextMeshProUGUI_Title == null)
                    _TextMeshProUGUI_Title = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_Title");
                return _TextMeshProUGUI_Title;
            }
        }

        public UnityEngine.RectTransform RectTransform_TitleDescBg
        {
            get
            {
                if(_RectTransform_TitleDescBg == null)
                    _RectTransform_TitleDescBg = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_TitleDescBg");
                return _RectTransform_TitleDescBg;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_TitleDesc
        {
            get
            {
                if(_TextMeshProUGUI_TitleDesc == null)
                    _TextMeshProUGUI_TitleDesc = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_TitleDesc");
                return _TextMeshProUGUI_TitleDesc;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_Content
        {
            get
            {
                if(_TextMeshProUGUI_Content == null)
                    _TextMeshProUGUI_Content = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_Content");
                return _TextMeshProUGUI_Content;
            }
        }

        public TMPro.TextMeshProUGUI TextMeshProUGUI_Process
        {
            get
            {
                if(_TextMeshProUGUI_Process == null)
                    _TextMeshProUGUI_Process = componentItemKey.GetObject<TMPro.TextMeshProUGUI>("TextMeshProUGUI_Process");
                return _TextMeshProUGUI_Process;
            }
        }

        public UnityEngine.RectTransform RectTransform_LoadingTitlebg
        {
            get
            {
                if(_RectTransform_LoadingTitlebg == null)
                    _RectTransform_LoadingTitlebg = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_LoadingTitlebg");
                return _RectTransform_LoadingTitlebg;
            }
        }

        public UnityEngine.RectTransform RectTransform_GameTips
        {
            get
            {
                if(_RectTransform_GameTips == null)
                    _RectTransform_GameTips = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_GameTips");
                return _RectTransform_GameTips;
            }
        }

        public UnityEngine.UI.Image Image_Slider
        {
            get
            {
                if(_Image_Slider == null)
                    _Image_Slider = componentItemKey.GetObject<UnityEngine.UI.Image>("Image_Slider");
                return _Image_Slider;
            }
        }

        /// <summary>
        /// 绑定按钮点击事件
        /// </summary>
        protected virtual void BindButtonEvents()
        {
        }

        /// <summary>
        /// 解绑按钮点击事件
        /// </summary>
        protected virtual void UnbindButtonEvents()
        {
        }

        protected virtual void ReleaseComponent()
        {
            UnbindButtonEvents();

            _Image_Bg = null;
            _TextMeshProUGUI_Title = null;
            _RectTransform_TitleDescBg = null;
            _TextMeshProUGUI_TitleDesc = null;
            _TextMeshProUGUI_Content = null;
            _TextMeshProUGUI_Process = null;
            _RectTransform_LoadingTitlebg = null;
            _RectTransform_GameTips = null;
            _Image_Slider = null;
            _componentItemKey = null;
        }
    }
}
