
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Fight
{
public sealed partial class Rank : Luban.BeanBase
{
    public Rank(JSONNode _buf) 
    {
        { if(!_buf["rank_id"].IsNumber) { throw new SerializationException(); }  RankId = _buf["rank_id"]; }
        { if(!_buf["rank_name"].IsString) { throw new SerializationException(); }  RankName = _buf["rank_name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static Rank DeserializeRank(JSONNode _buf)
    {
        return new Fight.Rank(_buf);
    }

    /// <summary>
    /// 排名
    /// </summary>
    public readonly int RankId;
    /// <summary>
    /// 段位名
    /// </summary>
    public readonly string RankName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -1377257590;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "rankId:" + RankId + ","
        + "rankName:" + RankName + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

