
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Fight
{
public partial class TbTest1
{
    private readonly System.Collections.Generic.Dictionary<int, Fight.Test1> _dataMap;
    private readonly System.Collections.Generic.List<Fight.Test1> _dataList;
    
    public TbTest1(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fight.Test1>();
        _dataList = new System.Collections.Generic.List<Fight.Test1>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Fight.Test1 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Fight.Test1.DeserializeTest1(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fight.Test1> DataMap => _dataMap;
    public System.Collections.Generic.List<Fight.Test1> DataList => _dataList;

    public Fight.Test1 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fight.Test1 Get(int key) => _dataMap[key];
    public Fight.Test1 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

