//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由UI绑定工具自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using Core;

namespace HotUpdate
{
    [SourceAttribute("Assets/GameRes/Prefabs/TestMain")]
    public partial class TestMainView
    {
        ComponentItemKey _componentItemKey;

        private UnityEngine.CanvasRenderer _CanvasRenderer_image;

        protected ComponentItemKey componentItemKey
        {
            get
            {
                if(_componentItemKey == null)
                    _componentItemKey = transform.GetComponent<ComponentItemKey>();
                return _componentItemKey;
            }
        }

        public UnityEngine.CanvasRenderer CanvasRenderer_image
        {
            get
            {
                if(_CanvasRenderer_image == null)
                    _CanvasRenderer_image = componentItemKey.GetObject<UnityEngine.CanvasRenderer>("CanvasRenderer_image");
                return _CanvasRenderer_image;
            }
        }

        protected virtual void ReleaseComponent()
        {
            _CanvasRenderer_image = null;
            _componentItemKey = null;
        }
    }
}
