//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由UI绑定工具自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UI;
using Core.Runtime;

namespace HotUpdate
{
    [SourceAttribute("Assets/GameRes/Prefabs/UI/TestMain")]
    public partial class TestMainView
    {
        ComponentItemKey _componentItemKey;

        private UnityEngine.CanvasRenderer _CanvasRenderer_BigBg123;
        private UnityEngine.RectTransform _RectTransform_TestBtn;
        private UnityEngine.UI.Button _Button_TestBtn;

        protected ComponentItemKey componentItemKey
        {
            get
            {
                if(_componentItemKey == null)
                    _componentItemKey = transform.GetComponent<ComponentItemKey>();
                return _componentItemKey;
            }
        }

        public UnityEngine.CanvasRenderer CanvasRenderer_BigBg123
        {
            get
            {
                if(_CanvasRenderer_BigBg123 == null)
                    _CanvasRenderer_BigBg123 = componentItemKey.GetObject<UnityEngine.CanvasRenderer>("CanvasRenderer_BigBg123");
                return _CanvasRenderer_BigBg123;
            }
        }

        public UnityEngine.RectTransform RectTransform_TestBtn
        {
            get
            {
                if(_RectTransform_TestBtn == null)
                    _RectTransform_TestBtn = componentItemKey.GetObject<UnityEngine.RectTransform>("RectTransform_TestBtn");
                return _RectTransform_TestBtn;
            }
        }

        public UnityEngine.UI.Button Button_TestBtn
        {
            get
            {
                if(_Button_TestBtn == null)
                    _Button_TestBtn = componentItemKey.GetObject<UnityEngine.UI.Button>("Button_TestBtn");
                return _Button_TestBtn;
            }
        }

        /// <summary>
        /// 绑定按钮点击事件
        /// </summary>
        protected virtual void BindButtonEvents()
        {
            Button_TestBtn?.onClick.AddListener(OnTestBtnClick);
        }

        /// <summary>
        /// 解绑按钮点击事件
        /// </summary>
        protected virtual void UnbindButtonEvents()
        {
            Button_TestBtn?.onClick.RemoveListener(OnTestBtnClick);
        }

        protected virtual void ReleaseComponent()
        {
            UnbindButtonEvents();

            _CanvasRenderer_BigBg123 = null;
            _RectTransform_TestBtn = null;
            _Button_TestBtn = null;
            _componentItemKey = null;
        }
    }
}
