//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由UI绑定工具自动生成，请勿手动修改
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using Core.Runtime;

namespace HotUpdate
{
    [SourceAttribute("Assets/GameRes/Prefabs/UI/Main/MainUI")]
    public partial class MainUIView
    {
        ComponentItemKey _componentItemKey;

        private UnityEngine.UI.Button _Button_settingBtn;
        private UnityEngine.UI.Button _Button_quitBtn;
        private Core.Runtime.FlippableImage _FlippableImage_gameObject;

        protected ComponentItemKey componentItemKey
        {
            get
            {
                if(_componentItemKey == null)
                    _componentItemKey = transform.GetComponent<ComponentItemKey>();
                return _componentItemKey;
            }
        }

        public UnityEngine.UI.Button Button_settingBtn
        {
            get
            {
                if(_Button_settingBtn == null)
                    _Button_settingBtn = componentItemKey.GetObject<UnityEngine.UI.Button>("Button_settingBtn");
                return _Button_settingBtn;
            }
        }

        public UnityEngine.UI.Button Button_quitBtn
        {
            get
            {
                if(_Button_quitBtn == null)
                    _Button_quitBtn = componentItemKey.GetObject<UnityEngine.UI.Button>("Button_quitBtn");
                return _Button_quitBtn;
            }
        }

        public Core.Runtime.FlippableImage FlippableImage_gameObject
        {
            get
            {
                if(_FlippableImage_gameObject == null)
                    _FlippableImage_gameObject = componentItemKey.GetObject<Core.Runtime.FlippableImage>("FlippableImage_gameObject");
                return _FlippableImage_gameObject;
            }
        }

        protected virtual void ReleaseComponent()
        {
            _Button_settingBtn = null;
            _Button_quitBtn = null;
            _FlippableImage_gameObject = null;
            _componentItemKey = null;
        }
    }
}
